transform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      dbname: dwh
      schema: public
      threads: 1
      user: postgres
      pass: postgres
